// Auto-generated by src/Image/generate-symbol-map.cjs
import { ReactComponent as chevron_down } from './Symbols/chevron.down.svg?component'
import { ReactComponent as chevron_left_square_fill } from './Symbols/chevron.left.square.fill.svg?component'
import { ReactComponent as chevron_right_square_fill } from './Symbols/chevron.right.square.fill.svg?component'
import { ReactComponent as chevron_right } from './Symbols/chevron.right.svg?component'
import { ReactComponent as heart } from './Symbols/heart.svg?component'
import { ReactComponent as info_circle } from './Symbols/info.circle.svg?component'
import { ReactComponent as person_crop_circle } from './Symbols/person.crop.circle.svg?component'
import { ReactComponent as photo_on_rectangle } from './Symbols/photo.on.rectangle.svg?component'
import { ReactComponent as rectangle_stack_badge_person_crop } from './Symbols/rectangle.stack.badge.person.crop.svg?component'
import { ReactComponent as rectangle_stack } from './Symbols/rectangle.stack.svg?component'
import { ReactComponent as square_and_arrow_up } from './Symbols/square.and.arrow.up.svg?component'
import { ReactComponent as xmark_circle_fill } from './Symbols/xmark.circle.fill.svg?component'

export const symbolMap = {
  'chevron.down': chevron_down,
  'chevron.left.square.fill': chevron_left_square_fill,
  'chevron.right.square.fill': chevron_right_square_fill,
  'chevron.right': chevron_right,
  'heart': heart,
  'info.circle': info_circle,
  'person.crop.circle': person_crop_circle,
  'photo.on.rectangle': photo_on_rectangle,
  'rectangle.stack.badge.person.crop': rectangle_stack_badge_person_crop,
  'rectangle.stack': rectangle_stack,
  'square.and.arrow.up': square_and_arrow_up,
  'xmark.circle.fill': xmark_circle_fill,
};
